apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-b-v1
  namespace: default
spec:
  sources:
    - name: service-a
      action: allow
      namespace: default
  destination:
    name: service-b-v1
    namespace: default
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-a
  namespace: default
spec:
  sources:
    - name: api-gateway
      action: allow
      namespace: default
  destination:
    name: 'service-a'
    namespace: default