apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: fake_service ## The name of the partition containing the service
spec:
  services:
    - name: service-c-v1 ## The name of the service you want to export
      consumers:
      - peer: dc1 ## The name of the peering connection that receives the service
    