apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: backend
spec:
  destination:
    name: backend
#   partition: tenant-1
  sources:
  - name: frontend
    action: allow
    partition: tenant-1