---
  apiVersion: consul.hashicorp.com/v1alpha1
  kind: ServiceDefaults
  metadata:
    name: documentdb
  spec:
    protocol: tcp
    destination:
      addresses:
        - "docdb-test.cluster-ck4qnrbriwav.eu-west-1.docdb.amazonaws.com"
      port: 27017

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: documentdb
      caFile: "/etc/ssl/certs/ca-certificates.crt"
      #sni: "docdb-test.cluster-ck4qnrbriwav.eu-west-1.docdb.amazonaws.com"

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: documentdb
spec:
  destination:
    name: documentdb
  sources:
    - name: frontend
      action: allow