---
  apiVersion: consul.hashicorp.com/v1alpha1
  kind: ServiceDefaults
  metadata:
    name: hcp-vault
  spec:
    protocol: http
    destination:
      addresses:
        - "do-not-delete-ever-v2-public-vault-cf6a1d76.5773df81.z1.hashicorp.cloud"
      port: 8200

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: hcp-vault
      #caFile: "/etc/ssl/certs/ca-certificates.crt"
      #sni: "do-not-delete-ever-v2-public-vault-cf6a1d76.5773df81.z1.hashicorp.cloud"