apiVersion: consul.hashicorp.com/v1alpha1         
kind: ServiceSplitter                             
metadata:                                         
  name: service-a                         
  namespace: default                                 
spec:
  splits:                                         
    - weight: 70                                  
      service: service-b-v1                            
      namespace: default                 
      partition: tenant-2                
    - weight: 30
      service: service-b-v2
      namespace: default
      partition: tenant-2
    
