apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: tenant-1
spec:
  services:
  - name: mesh-gateway
    consumers:
    - partition: tenant-2
  - name: mesh-gateway
    consumers:
    - partition: default