apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-a-to-service-a
spec:
  destination:
    name: service-a
#   partition: tenant-1
  sources:
  - name: service-a
    action: allow
    partition: default