apiVersion: consul.hashicorp.com/v1alpha1
kind: PeeringAcceptor
metadata:
  name: ap2-dc2-default
spec:
  peer:
    secret:
      name: "peering-token-dc2-default"
      key: "data"
      backend: "kubernetes"