apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: dc1-senvice-b-to-dc2-service-c
spec:
  destination:
    name: service-c-v1
  sources:
   - name: service-b-v1
     action: allow
     peer: dc1-tenant-2