apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: nginx-resolver
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
        - peer: 'backend'
          service: 'nginx'
          namespace: 'default'
---
