# Service to expose chatapp
apiVersion: v1
kind: Service
metadata:
  name: chatapp
spec:
  selector:
    app: chatapp
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatapp
---
# chatapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
  labels:
    app: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "false"
#       "consul.hashicorp.com/connect-service-upstreams": "service-c:9091"
        "consul.hashicorp.com/connect-service-upstreams": "example-docdb:27017"
         #For the upstream line, this points to the #"<servicename>.<consul-namespace>.<partitionname>:<port#>" of the upstream service.
         #If its in the same partition and namespace, it can be omitted, ex:
#        "consul.hashicorp.com/connect-service-upstreams": "service-c:9091"
    spec:
      serviceAccountName: chatapp
      containers:
      - name: chatapp
        image: lhaig/anon-app:dark-0.03
        ports:
        - containerPort: 5000
        env:
        - name: "MONGODB_SERVER"
          # value: "127.0.0.1"
          value: "localhost"              
        - name: "MONGODB_PORT"
          # value: "27017"
          # To connect to the upstream mongodb pointing to local upstream port
          value: "27017"
        - name: "MONGODB_COL"
          value: "chatappapp"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: chatapp
spec:
  protocol: "http"
