apiVersion: consul.hashicorp.com/v1alpha1
kind: TerminatingGateway
metadata:
  name: terminating-gateway
spec:
  services:
    - name: example-docdb
      sni: 'example-docdb-cluster.cluster-cwwnbexip9py.eu-west-2.docdb.amazonaws.com'
      caFile: /consul/userconfig/my-secret/rds-combined-ca-bundle.pem
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: example-docdb
spec:
  destination:
    name: example-docdb
  sources:
    - name: chatapp
      action: allow