apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: nginx
spec:
  redirect:
    service: nginx
    peer: backend
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: MeshService
metadata:
  name: mesh-nginx
spec:
  name: nginx
