
apiVersion: consul.hashicorp.com/v1alpha1
kind: MeshService
metadata:
  name: mesh-nginx
spec:
  name: nginx
  peer: backend
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: mesh-nginx
spec:
 destination:
   name: mesh-nginx
 sources:
   - name: api-gateway
     action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: mesh-nginx
spec:
  splits:
    - weight: 100
      service: mesh-nginx