apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  accessLogs:
    enabled: true
  meshGateway:
    mode: local
  config:
    protocol: http
    envoy_prometheus_bind_addr: '0.0.0.0:20200'
