apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: products-api
  namespace: default
spec:
  sources:
    - name: public-api
      action: allow
      namespace: default
      peer: dc1-dc2-default
  destination:
    name: products-api
    namespace: default
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
  namespace: default
spec:
  sources:
    - name: public-api
      action: allow
      namespace: default
      peer: dc1-dc2-default
  destination:
    name: payments
    namespace: default
