apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
      app: frontend
  template:
    metadata:
      labels:
        service: frontend
        app: frontend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: "2"
        consul.hashicorp.com/service-tags: "v2"
        consul.hashicorp.com/service-metrics-enabled: "true"
        consul.hashicorp.com/service-metrics-path: "/metrics"
        consul.hashicorp.com/service-metrics-port: "3000"
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
        consul.hashicorp.com/envoy-extra-args: "--log-level info --component-log-level upstream:debug,connection:info"
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: docker.io/caique2203/test-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_PUBLIC_API_URL
              value: "/"
          resources:
            limits:
              cpu: 500m
              memory: 512M
            requests:
              cpu: 500m
              memory: 512M