apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: default
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: service-b-v1
          hosts: ["*"]
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: igw-service-b-v1
spec:
  destination:
    name: service-b-v1
  sources:
    - name: ingress-gateway
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: igw-service-b-v2
spec:
  destination:
    name: service-b-v2
  sources:
    - name: ingress-gateway
      action: allow      