apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-b-v1-to-service-a
spec:
  destination:
    name: service-b-v1
#   partition: tenant-1
  sources:
  - name: service-a
    action: allow
    partition: tenant-1
  - name: service-a
    action: allow
    partition: default
  - name: ingress-gateway
    action: allow
    partition: tenant-1
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-b-v2-to-service-a
spec:
  destination:
    name: service-b-v2
#   partition: tenant-1
  sources:
  - name: service-a
    action: allow
    partition: tenant-2
  - name: service-a
    action: allow
    partition: tenant-1
  - name: service-a
    action: allow
    partition: default
  - name: ingress-gateway
    action: allow
    partition: tenant-1    
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-c-v1-to-service-b
spec:
  destination:
    name: service-c-v1
#   partition: tenant-1
  sources:
  - name: service-b-v1
    action: allow
  - name: service-b-v2
    action: allow
  - name: service-a
    action: allow    
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-c-v2-to-service-b
spec:
  destination:
    name: service-c-v2
#   partition: tenant-1
  sources:
  - name: service-b-v1
    action: allow
  - name: service-b-v2
    action: allow      
