apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: service-b-v1
  namespace: default
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
      - service: service-b-v2
        namespace: default