apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: service-a
  namespace: default
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
      - peer: 'ap2-dc2-default'