apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-c-v1-to-service-b
spec:
  destination:
    name: service-c-v1
#   partition: tenant-1
  sources:
  - name: service-b-v1
    action: allow
  - name: service-b-v2
    action: allow  