global:
  name: frontend
  enabled: false
  image: hashicorp/consul-enterprise:1.21.8-ent
  logLevel: "debug"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
  peering:
    enabled: true
  adminPartitions:
    enabled: true
    name: servicos-a2
  enableConsulNamespaces: true
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key 
      secretKey: tls.key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token 
      secretKey: token
# client:
#  enabled: false
#  grpc: true
externalServers:
  enabled: true
  hosts: [acd82b0b3d1364795bc31b7b362e65e5-1633282915.eu-west-2.elb.amazonaws.com]
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://0F4931A4A882E7D2727E6B4CC6040D6F.gr7.eu-west-2.eks.amazonaws.com
controller: 
  enabled: true
connectInject:
  enabled: true
  default: true                
  transparentProxy:
    defaultEnabled: true         # Default
    logLevel: "debug"
# envoyExtraArgs: "--log-level debug"
metrics:
  defaultEnabled: true
  defaultEnableMerging: true
  apiGateway:
    manageExternalCRDs: true
    # Configuration settings for the GatewayClass
    managedGatewayClass:
      # Defines the type of service created for gateways (e.g. LoadBalancer, ClusterIP, NodePort)
      # LoadBalancer is primarily used for cloud deployments.
      serviceType: LoadBalancer  
terminatingGateways:
  enabled: true
meshGateway:
  enabled: true
  
#  replicas: 1
# service:
#   enabled: true
#   type: 'LoadBalancer'
# wanAddress:
#   source: Service
