global:
  name: consul
  enabled: false
  image: hashicorp/consul-enterprise:1.15.2-ent
  imageEnvoy: "envoyproxy/envoy-alpine:v1.25.1"
  imageConsulDataplane: "hashicorp/consul-dataplane:1.1.0"
  logLevel: "debug"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
 
  adminPartitions:
    enabled: true
    name: tenant-1

  enableConsulNamespaces: true

  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key 
      secretKey: tls.key

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token 
      secretKey: token

# client:
#  enabled: false
#  grpc: true

externalServers:
  enabled: true
  hosts: [a57bda547d5d144bf9e706fcc04dc77e-888663621.eu-west-2.elb.amazonaws.com]
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://F245AB38148F50252588A27F9B5E9738.gr7.eu-west-2.eks.amazonaws.com
  
controller: 
  enabled: true

connectInject:
  enabled: true
  default: true                
  transparentProxy:
    defaultEnabled: true         # Default
    logLevel: "debug"
# envoyExtraArgs: "--log-level debug"
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true

ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: 'LoadBalancer'
  wanAddress:
    source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

terminatingGateways:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
# service:
#   enabled: true
#   type: 'LoadBalancer'
# wanAddress:
#   source: Service
