global:
  name: consul
  enabled: false
  image: hashicorp/consul-enterprise:1.21.8-ent
  logLevel: "debug"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
  peering:
    enabled: true 
  adminPartitions:
    enabled: true
    name: tenant-a2

  enableConsulNamespaces: true

  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key 
      secretKey: tls.key

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token 
      secretKey: token

# client:
#  enabled: false
#  grpc: true

externalServers:
  enabled: true
  hosts: [a37536c2ac7324803a04ba6c3e1c3665-2020796093.eu-west-2.elb.amazonaws.com]
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://E81E1FD1FDB21A5CE681EF221C0CA37F.gr7.eu-west-2.eks.amazonaws.com
  
controller: 
  enabled: true

connectInject:
  enabled: true
  default: true                
  transparentProxy:
    defaultEnabled: true         # Default
    logLevel: "debug"
# envoyExtraArgs: "--log-level debug"
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true

ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      service:
        type: 'LoadBalancer'
  wanAddress:
    source: Service
#       annotations: |
#         'service.beta.kubernetes.io/aws-load-balancer-internal': "false"

terminatingGateways:
  enabled: true
meshGateway:
  enabled: true
  replicas: 1
# service:
#   enabled: true
#   type: 'LoadBalancer'
# wanAddress:
#   source: Service
