global:
  name: frontend
  enabled: false
  image: hashicorp/consul-enterprise:1.21.8-ent
  logLevel: "debug"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
    enableConsulNamespaces: true
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key 
      secretKey: tls.key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token 
      secretKey: token
controller:
  enabled: true
connectInject:
  enabled: true
  default: true                 
  transparentProxy:
    defaultEnabled: true         # Default      
  apiGateway:
    manageExternalCRDs: true
    managedGatewayClass:
      serviceType: LoadBalancer  
externalServers:
  enabled: true
  hosts: [a7df82ce73708406c94a467a164ea07b-1222045949.eu-west-2.elb.amazonaws.com]
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://8C6A80802D23B07ADBE91B62DCFBDB25.gr7.eu-west-2.eks.amazonaws.com
# envoyExtraArgs: "--log-level debug"
# meshGateway:
#   enabled: true
#   replicas: 1
metrics:
  defaultEnabled: true
  defaultEnableMerging: true
