global:
  name: client
  enabled: false
  image: hashicorp/consul-enterprise:1.22.2-ent
  logLevel: "debug"
  enterpriseLicense:
    secretName: consul-ent-license
    secretKey: key
    enableConsulNamespaces: true
  tls:
    enabled: true
    caCert:
      secretName: consul-ca-cert 
      secretKey: tls.crt
    caKey:
      secretName: consul-ca-key 
      secretKey: tls.key
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-partitions-acl-token 
      secretKey: token
connectInject:
  enabled: true
  default: true                 
  transparentProxy:
    defaultEnabled: true         # Default      
  apiGateway:
    manageExternalCRDs: true
    # Configuration settings for the GatewayClass
    managedGatewayClass:
      # Defines the type of service created for gateways (e.g. LoadBalancer, ClusterIP, NodePort)
      # LoadBalancer is primarily used for cloud deployments.
      serviceType: LoadBalancer  
externalServers:
  enabled: true
  hosts: [a5c05b5e5966e4b49880e14da385fe34-1935114291.eu-west-2.elb.amazonaws.com]
  tlsServerName: server.dc1.consul
  k8sAuthMethodHost: https://818BC96A5B7C07BDBBD71557DA247970.gr7.eu-west-2.eks.amazonaws.com
# envoyExtraArgs: "--log-level debug"
meshGateway:
  enabled: true
  replicas: 1
  metrics:
    defaultEnabled: true
    defaultEnableMerging: true
