apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
 # namespace: consul
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: service-a
          partition: tenant-1
          namespace: default
          hosts: ["*"]
