apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: service-b-v1-to-service-a
spec:
  destination:
    name: service-b-v1
#   partition: tenant-1
  sources:
  - name: service-a
    action: allow