apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: test
  namespace: default
spec:
  routes:
    - match:
        http:
          queryParam:
              - name: dark
                exact: "true"
      destination:
        service: test-dark