apiVersion: consul.hashicorp.com/v1alpha1         
kind: ServiceSplitter                             
metadata:                                         
  name: test
  namespace: default                                 
spec:
  splits:                                         
    - weight: 50                                  
      service: test                            
      namespace: default                                 
    - weight: 50
      service: test-dark
      namespace: default
