# Service to expose todo
apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  selector:
    app: todo
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo
---
# todo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/transparent-proxy": "false"
#       "consul.hashicorp.com/connect-service-upstreams": "service-c:9091"
        "consul.hashicorp.com/connect-service-upstreams": "service-b-v1:9091"
         #For the upstream line, this points to the #"<servicename>.<consul-namespace>.<partitionname>:<port#>" of the upstream service.
         #If its in the same partition and namespace, it can be omitted, ex:
#        "consul.hashicorp.com/connect-service-upstreams": "service-c:9091"
    spec:
      serviceAccountName: todo
      containers:
      - name: todo
        image: guybarros/nest-todo-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: "MONGODB_SERVER"
          # value: "127.0.0.1"
          value: "localhost"              
        - name: "MONGODB_PORT"
          # value: "27017"
          # To connect to the upstream mongodb pointing to local upstream port
          value: "9091"
        - name: "MONGODB_COL"
          value: "todoapp"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: todo
spec:
  protocol: "http"
