apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: managed-aws-rds
spec:
  protocol: tcp
  destination:
    addresses:
     - "backend.cwwnbexip9py.eu-west-2.rds.amazonaws.com"
    port: 5432